### PR TITLE
Added Sigmar Family from Google Summer of type sprint

### PR DESCRIPTION
**Pull request by m4rc1e**
Adding @aoifemooney and team's work to this repo.

## Sigmar

**FB Report**
```
(venv)Marc:fontbakery marc$ fontbakery check-googlefonts /Users/marc/Documents/googlefonts/manual_font_cleaning/sigmarone/fonts/Sigmar-Regular.ttf -C -l FAIL
There is a total of 133 checks on <Section: Default>.
Start ... running 133 individual check executions.
>> com.google.fonts/check/028
   Check font has a license.
 * FAIL: No license file was found. Please add an OFL.txt or a LICENSE.txt file. If you are running fontbakery on a Google Fonts upstream repo, which is fine, just make sure there is a temporary license file in the same folder. [code: none]

   Result: FAIL

>> com.google.fonts/check/037 with ((u'font[0]', '/Users/marc/Documents/googlefonts/manual_font_cleaning/sigmarone/fonts/Sigmar-Regular.ttf'),)
   Checking with Microsoft Font Validator.
 * FAIL: MS-FonVal: The xAvgCharWidth field does not equal the calculated value DETAILS: actual = 675, calc = 539
 * FAIL: MS-FonVal: There are undefined bits set in fsSelection field DETAILS: Bit(s) 7
 * FAIL: MS-FonVal: Intersecting contours DETAILS: Glyph index 64
 * FAIL: MS-FonVal: Intersecting contours DETAILS: Glyph index 89
 * FAIL: MS-FonVal: Intersecting contours DETAILS: Glyph index 188
 * FAIL: MS-FonVal: Intersecting contours DETAILS: Glyph index 246
 * FAIL: MS-FonVal: Intersecting contours DETAILS: Glyph index 302
 * FAIL: MS-FonVal: Intersecting contours DETAILS: Glyph index 307
 * FAIL: MS-FonVal: Intersecting contours DETAILS: Glyph index 318
 * FAIL: MS-FonVal: Intersecting contours DETAILS: Glyph index 322
 * FAIL: MS-FonVal: Intersecting contours DETAILS: Glyph index 405
 * FAIL: MS-FonVal: Intersecting contours DETAILS: Glyph index 456
 * FAIL: MS-FonVal: Intersecting contours DETAILS: Glyph index 466
 * FAIL: MS-FonVal: Intersecting contours DETAILS: Glyph index 558
 * FAIL: MS-FonVal: Intersecting contours DETAILS: Glyph index 583
 * FAIL: MS-FonVal: Intersecting contours DETAILS: Glyph index 670
 * FAIL: MS-FonVal: Intersecting contours DETAILS: Glyph index 710
 * FAIL: MS-FonVal: Intersecting contours DETAILS: Glyph index 761
 * FAIL: MS-FonVal: Intersecting contours DETAILS: Glyph index 819

   Result: FAIL

======== <Section: Default> ========
133 checks in section


Section results:

    ERROR: 0
    FAIL: 2
    WARN: 6
    SKIP: 54
    INFO: 6
    PASS: 65

======== END <Section: Default> ========

Total:

    ERROR: 0
    FAIL: 2
    WARN: 6
    SKIP: 54
    INFO: 6
    PASS: 65

[PSSSSSPPPPPPPFSSSSSSSSSSSSPPPWPPSPPPPWPPFSSPPPPPPWPPPPIPIPIPPPPIPPWWPPPPPPPPPPPPPSSSSSSSSSSSSSSSSSSSSSSSSPSSPPPPWSSPPPPPPPPPIISSSSSSP] 100%

DONE!

```
Summary: License fail will be solved when the fonts are added to google/fonts

**Waterfall Win7 IE9**
desktop_windows_7_ie_9 0_

**Glyphs all OSX Safari**
desktop_os_x_el_capitan_safari_9 1_

[SigmarImg.zip](https://github.com/googlefonts/sigmarone/files/1819052/SigmarImg.zip)

## SigmarOne

**Fb Report**
```
Start ... running 133 individual check executions.
>> com.google.fonts/check/028
   Check font has a license.
 * FAIL: No license file was found. Please add an OFL.txt or a LICENSE.txt file. If you are running fontbakery on a Google Fonts upstream repo, which is fine, just make sure there is a temporary license file in the same folder. [code: none]

   Result: FAIL

>> com.google.fonts/check/037 with ((u'font[0]', '/Users/marc/Documents/googlefonts/manual_font_cleaning/sigmarone/fonts/SigmarOne-Regular.ttf'),)
   Checking with Microsoft Font Validator.
 * FAIL: MS-FonVal: The xAvgCharWidth field does not equal the calculated value DETAILS: actual = 752, calc = 622
 * FAIL: MS-FonVal: There are undefined bits set in fsSelection field DETAILS: Bit(s) 7

   Result: FAIL

======== <Section: Default> ========
133 checks in section


Section results:

    ERROR: 0
    FAIL: 2
    WARN: 6
    SKIP: 54
    INFO: 5
    PASS: 66

======== END <Section: Default> ========

Total:

    ERROR: 0
    FAIL: 2
    WARN: 6
    SKIP: 54
    INFO: 5
    PASS: 66

[PSSSSSPPPPPPPFSSSSSSSSSSSSPPPWPPSPPPPWPPFSSPPPPPPWPPPPIPIPIPPPPIPPWWPPPPPPPPPPPPPSSSSSSSSSSSSSSSSSSSSSSSSPSSPPPPWSSPPPPPPPPPPISSSSSSP] 100%

DONE!
```

**Diff Browsers**
```
Regression Report:

Fonts: ["SigmarOne-Regular.ttf"]

View: glyphs-modified
PASSED: Desktop_OS_X_El_Capitan_safari_9.1_.jpg is the same

View: waterfall
WARNING: Desktop_Windows_7_chrome_50.0_.jpg is different by 427 pixels
WARNING: Desktop_Windows_10_edge_15.0_.jpg is different by 462 pixels
WARNING: Desktop_Windows_7_ie_9.0_.jpg is different by 462 pixels
WARNING: Desktop_Windows_7_firefox_45.0_.jpg is different by 7574 pixels
WARNING: Desktop_OS_X_El_Capitan_safari_9.1_.jpg is different by 112 pixels
WARNING: Google_Nexus_5_android_5.0_Android_Browser_.jpg is different by 53 pixels

```

**Win 7 Firefox 45**
desktop_windows_7_firefox_45 0_

**OSX Safari**
desktop_os_x_el_capitan_safari_9 1_

### CODE REVIEW

**Comment by davelab6** [comment]
I don't get it, it looks like nothing was modified?

**Comment by m4rc1e** [comment]
@davelab6 This PR includes a new family and source called Sigmar.glyphs. 

In SigmarOne, I have update the Copyright string only.

When I pr at google/fonts, I'll be creating a new family in a dir called ofl/sigmar. I'll also update ofl/sigmarone to the font which has the updated copyright.

**Comment by davelab6** [comment]
Hmm. Ok cool, I propose to stop work on this and move to another family so
I can better decide what to do.

**Comment by m4rc1e** [comment]
Totally understood. 

Ideally we want both SigmarOne and Sigmar in the same glyphs source. This will require some stitching and we may need to update SigmarOne to reflect the new design changes made in Sigmar.

**Comment by davelab6** [comment]
Yeah thats what I want to reconsider, and discuss with @aoifemooney

**Comment by aoifemooney** [comment]
Oops oops! Sorry for the extended delay—are you both free on Thursday morning EST by any chance? 

A

**Comment by davelab6** [comment]
Per https://github.com/googlefonts/sigmarone/commits/main I updated this repo with the latest commits from @aoifemooney in her repo that weren't PR'd upstream here yet. 

@Fonthausen please review @m4rc1e 's comments above and maybe chat with him next week

**Pull request closed without merging**
